language: node_js
node_js:
  - "0.12"
  - "4.4"
  - "5.9"
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "5.9" 
script: "npm run-script test-ci"
after_script: "npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls"
